---
title: "Pharmacy report main"
author: "Chris Beeley"
date: "24/01/2022"
output: html_document
resource_files:
- R/calc_mode.R
- R/drug_quantity.R
- R/make_tsibble.R
- R/pharmacyReports-package.R
- R/utils-pipe.R
- pharmacyReports.Rproj
- secret/source_shiny_live.R
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(magrittr)
library(extraDistr)
library(feasts)
library(urca)

files.sources = list.files(here::here("R/"), full.names = TRUE)
purrr::walk(files.sources, ~ source(., local = knitr::knit_global()))

source(here::here("secret", "source_shiny_live.R"))

```

## Site 100, Supplier AAH

```{r}

product = initial_product_list
w_order = w_order_log_df1
requis = w_requis_df1

DT::datatable(
  inventory_reorder(site = 100, 
                    supplier = "AAH", 
                    product,
                    w_order, 
                    requis,
                    holidays = get_holidays(),
                    updateProgress),
                    rownames = FALSE, 
                    extensions = 'Buttons', 
                    options = list(dom = 'Blfrtip',
                                   buttons = c('copy', 'csv', 'excel', 
                                               'pdf', 'print'))
)


```

