# WARNING - Generated by {fusen} from /dev/flat_helper-functions.Rmd: do not edit by hand

test_that("Helper functions", {
  
  holidays <- get_holidays
  
  testthat::expect_gt(length(holidays), 0)

})
